services:
  server:
    container_name: fashion-erp
    build:
      context: .
      target: builder
    ports:
      - '8080:8080'
    environment:
      SWAGGER_UI: true
      # This needs to be changed
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fashion_erp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_URI: redis
      MINIO_ENDPOINT: http://minio:9000
    depends_on:
      - redis
      - postgres
      - minio

  postgres:
    image: postgres:15-alpine
    container_name: fashion-erp-db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fashion_erp
    ports:
      - "5432:5432"
    volumes:
      - fashion_erp_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: fashion-erp-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    depends_on:
      - redis

  minio:
    image: minio/minio:latest
    container_name: fashion-erp-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: adminpassword
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  fashion_erp_pg_data:
  redis_insight_data:
  minio_data:
