name: fashion-erp CI

on:
  push:
    branches: [ "main", "staging"]
    paths:
      - 'server/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "main", "staging"]
    paths:
      - 'server/**'

env:
  WORKING_DIR: ./server
  JAVA_VERSION: '17'

jobs:
  style-and-compile:
    name: Formatting & Style & Architecture (Fast Fail)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: server/pom.xml

      - name: Run Spotless Check
        run: mvn spotless:check
      
      - name: Test Compilation
        run: mvn test-compile
      
      - name: Run Architecture Tests (Fast Fail)
        run: mvn test -Dgroups="ArchitectureTests"

  test:
    name: Integration & Unit Tests
    needs: style-and-compile
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      checks: write
    
    defaults:
      run:
        working-directory: ./server

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fashion-erp
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17 with Caching
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'maven'
        cache-dependency-path: server/pom.xml
    
    # TODO : This might be necessary later, but not now
    # This was copied from deepdame, so we might follow the same
    # approach later on

    # - name: Run Key Generation
    #   run: |
    #     chmod +x keygen.sh
    #     ./keygen.sh

    - name: Run Tests
      run: mvn test
      env:
        # Postgres Config
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/fashion-erp
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

    - name: Enforce 60% Code Coverage
      run: mvn jacoco:check