name: fashion-erp CD

on:
  push:
    branches: [ "dev/ilyass"]

jobs:
  server-cd:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Deploy the server
        working-directory: ./server
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
